Add VPN commands
ffxiv-teamcraft/discord-bot pull request #42
Opened 2022-07-03 07:58 UTC by ayyaruq

The default case is generic VPN info, additionally added some more specific info. Happy to reword if desired. The other files I just cleaned up whitespace since it was pretty inconsistent and no spaces seemed more common.

2022-07-03 17:34 UTC, ArcaneDisgea requested changes
Need to [import](https://github.com/ffxiv-teamcraft/discord-bot/blob/master/src/command_handler.ts#L23) and add to [command_handler](https://github.com/ffxiv-teamcraft/discord-bot/blob/master/src/command_handler.ts#L49) for it to work. Commands are not automatically pulled from the commands dir and registered.

2022-07-04 05:24 UTC, Supamiu submitted a review, later dismissed

2022-07-05 04:15 UTC, ayyaruq commented
Handled, ready for merging.

2022-07-05 06:39 UTC, Supamiu approved these changes

2022-07-05 06:40 UTC, merged